// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

#include "AD9854.h"
#include "lvgl.h"

static lv_obj_t *num_keyboard;
static lv_coord_t ui_Chart2_series_1_array[] = { 
    0, 5, 15, 30, 55, 80, 95, 100, 95, 80,
    55, 30, 15, 5, 0, 5, 15, 30, 55, 80
};
static lv_coord_t sin_wave[] = {50,68,84,93,98,93,84,68,50,32,16,8,1,8,16,32,50,68,84,93};
static lv_coord_t square_wave[] = {100,100,100,100,100,0,0,0,0,0,100,100,100,100,100,0,0,0,0,0};
static void kb_ready_handler(lv_event_t * e) {
    // ??????(?????)
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, num_keyboard);
    lv_anim_set_values(&a, 0, lv_obj_get_width(num_keyboard));
    lv_anim_set_time(&a, 300);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_start(&a);
    
    lv_obj_add_flag(num_keyboard, LV_OBJ_FLAG_HIDDEN); // ????
}

static void ta_event_handler(lv_event_t * e) {
    if(e->code == LV_EVENT_CLICKED) {
        // ??????(?????)
        lv_anim_t a;
        lv_anim_init(&a);
        lv_anim_set_var(&a, num_keyboard);
        lv_anim_set_values(&a, lv_obj_get_width(num_keyboard), 0);
        lv_anim_set_time(&a, 300);
        lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_x);
        lv_anim_start(&a);
        
        lv_obj_clear_flag(num_keyboard, LV_OBJ_FLAG_HIDDEN);
        lv_keyboard_set_textarea(num_keyboard, ui_TextArea2); // ?????[1](@ref)
    }
}
static void button_callback(lv_event_t * e) 
{
    if(e->code == LV_EVENT_CLICKED) {
        // 1. ?????(?????????ui_TextArea2)
        const char *input = lv_textarea_get_text(ui_TextArea2);
        int freq = input[0] ? atoi(input) : 0;  // ????
        
        // 2. ??????(?????????ui_Dropdown2)
        uint16_t unit = lv_dropdown_get_selected(ui_Dropdown2);
        
        // 3. ????(??????????)
        switch(unit) {
            case 0: break;           // Hz
            case 1: freq *= 1000;     // KHz
            case 2: freq *= 1000000;  // MHz
        }

        // 4. ??????(????????ui_Roller2)
        uint16_t wave = lv_roller_get_selected(ui_Roller2);

        // 5. ??????(????????ui_Chart2)
        lv_chart_series_t *series = lv_chart_get_series_next(ui_Chart2, NULL);
        if(series) {
            lv_chart_set_ext_y_array(ui_Chart2, series, 
                (wave == 0) ? sin_wave : square_wave);
            lv_chart_refresh(ui_Chart2);  // ??????
        }
				AD9854_SetSine(freq, 4095);
    }
}

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller2 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_Roller2, "sin\nsquare", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller2, 60);
    lv_obj_set_height(ui_Roller2, 146);
    lv_obj_set_x(ui_Roller2, -121);
    lv_obj_set_y(ui_Roller2, -18);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x3C4346), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 1);
    lv_obj_set_y(ui_Label2, -97);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "AD9854_DDS");

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 119);
    lv_obj_set_height(ui_Button2, 29);
    lv_obj_set_x(ui_Button2, 89);
    lv_obj_set_y(ui_Button2, 78);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x5B6F77), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button2, lv_color_hex(0xEAE2E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 84);
    lv_obj_set_y(ui_Label1, 79);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "output");

    ui_Chart2 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart2, 135);
    lv_obj_set_height(ui_Chart2, 108);
    lv_obj_set_x(ui_Chart2, 88);
    lv_obj_set_y(ui_Chart2, -14);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
																																 
		lv_chart_set_point_count(ui_Chart2, sizeof(ui_Chart2_series_1_array)/sizeof(lv_coord_t)); 
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, 100);
    lv_obj_set_height(ui_TextArea2, 32);
    lv_obj_set_x(ui_TextArea2, -35);
    lv_obj_set_y(ui_TextArea2, -25);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Enter here...");

    ui_Dropdown2 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_Dropdown2, "Hz\nKHz\nMHz");
    lv_obj_set_width(ui_Dropdown2, 62);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, -16);
    lv_obj_set_y(ui_Dropdown2, 20);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -43);
    lv_obj_set_y(ui_Label4, -58);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "frequence");
		    // ????????(???????)
    num_keyboard = lv_keyboard_create(ui_Screen1);
    lv_obj_set_size(num_keyboard, 150, 180);          // ????
    lv_obj_align(num_keyboard, LV_ALIGN_RIGHT_MID, 0, 0); // ????[3](@ref)
    lv_keyboard_set_mode(num_keyboard, LV_KEYBOARD_MODE_NUMBER); // ?????[1,7](@ref)
    lv_obj_add_flag(num_keyboard, LV_OBJ_FLAG_HIDDEN); // ????
    
    // ????(?????????)
    lv_obj_add_event_cb(ui_TextArea2, ta_event_handler, LV_EVENT_CLICKED, NULL); // ???????[3](@ref)
    lv_obj_add_event_cb(num_keyboard, kb_ready_handler, LV_EVENT_READY, NULL);  // ??????[3](@ref)
		lv_obj_add_event_cb(ui_Button2, button_callback, LV_EVENT_CLICKED, NULL);
}
